onlyBuiltDependencies:
  - esbuild

overrides:
  '@octokit/request-error@>=1.0.0 <5.1.1': '>=5.1.1'
  esbuild@<=0.24.2: '>=0.25.0'
  '@octokit/request@>=1.0.0 <8.4.1': '>=8.4.1'
  '@octokit/plugin-paginate-rest@>=1.0.0 <9.2.2': '>=9.2.2'
